version: '3.8'
services:
  sistema_de_turnos:
    container_name: 'SistemaDeTurnos'
    build:
      context: .
    volumes:
      - ..:/home/volume
      - sistema-de-turnos-bashhistory:/commandhistory
    links:
      - db:database
    working_dir: /home/volume
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - sleep infinity

  db:
    container_name: 'Database'
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    restart: unless-stopped

volumes:
  sistema-de-turnos-bashhistory:
